twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        # Namespace & directory for components
        Selene\CMSBundle\Twig\Components\: 'vendor/selenesoftware/cms-bundle/templates/components/'
        App\Twig\Components\: 'components'
