services:
  tailscale:
    image: tailscale/tailscale
    container_name: symfony_tailscale
    environment:
      - TS_AUTHKEY=tskey-auth-kyANJf5LEP11CNTRL-Xfqg2tNmM3LxDJzPABBbxKVDpzPzR8cG
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    network_mode: "host"  # You can leave this to use the host network for Tailscale
    volumes:
      - /var/lib/tailscale:/var/lib/tailscale
    command: tailscaled

  nginx:
    image: nginx:latest
    # user: "nginx"
    container_name: symfony_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx
      - .:/var/www/symfony:rw
      # - ./php-fpm.sock:/var/run/php-fpm.sock:rw
      - ./var/cache/nginx:/var/cache/nginx
      - ./var/log/nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      - app-network

  php:
    image: php:8.3-fpm
    # user: "nginx"
    container_name: symfony_php
    volumes:
      - .:/var/www/symfony:rw
      - ./php/php.ini:/usr/local/etc/php/php.ini
      # - ./php-fpm.sock:/var/run/php-fpm.sock
    working_dir: /var/www/symfony
    environment:
      - APP_ENV=dev
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: symfony_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: symfony_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: symfony_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: symfony_mailhog
    ports:
      - "8025:8025"
    networks:
      - app-network

volumes:
  mysql_data:
  es_data:
  nginx:
    driver: local
  php-fpm-sock:
    driver: local

networks:
  app-network:
    driver: bridge
