controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# seleneCMSBundle:
#     resource: '@seleneCMS/config/routes/cms-bundle_routing.yaml'

